name: build-version
description: 'Get the build version for the workflow run.'
inputs:
  run_number:
    required: true
outputs:
  version:
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Get build version
      id: version
      run: echo "::set-output name=version::${{ steps.date.outputs.date }}.${{ run_number }}"
