name: build-version
description: 'Get the build version for the workflow run.'
inputs:
  run_number:
    description: "The run number."
    required: true
outputs:
  display-version:
    description: "The display version number (major.minor.feature)."
    value: ${{ steps.display-version.outputs.display-version }}

  full-version:
    description: "The full version number (major.minor.feature.build)."
    value: ${{ steps.full-version.outputs.full-version }}

runs:
  using: "composite"
  steps:
    - name: Get display version
      id: display-version
      run: echo "::set-output name=display-version::$(date +'%Y.%m.%d')"
      shell: pwsh

    - name: Get full version
      id: full-version
      run: echo "::set-output name=full-version::${{ steps.display-version.outputs.display-version }}.${{ inputs.run_number }}"
      shell: pwsh
