# This is a basic workflow to help you get started with Actions

name: just-playing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  just-playing:
    runs-on: windows-latest

    steps:
      - name: Get current date
        id: display-version
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Get build version
        id: version
        run: echo "::set-output name=build-version::${{ steps.display-version.outputs.date }}.${{ github.run_number }}"

      - name: What's the build version
        run: echo "build-version is ${{ steps.version.outputs.build-version }}"

      - name: Using Composite
        id: comp
        uses: donshephard/AlphaTrust/actions/build-version@v2
        with:
          run_number: ${{ github.run_number }}

      - name: Display version
        run: echo "display-version is ${{ steps.comp.outputs.display-version }}"

      - name: Full version
        run: echo "full-version is ${{ steps.comp.outputs.full-version }}"
