# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  alphatrust-nuget:
    runs-on: windows-latest

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'AlphaTrust.NuGet/AlphaTrust.NuGet.sln'

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore NuGet packages
      run: nuget restore 'AlphaTrust.NuGet'
      
    - name: Build AlphaTrust.NuGet
      run: msbuild $SOLUTION /p:Configuration=Release
