# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  alphatrust-nuget:
    runs-on: windows-latest
    env:
      SOLUTION: AlphaTrust.NuGet\AlphaTrust.NuGet.sln
      FOLDER: AlphaTrust.NuGet
      CONFIG: Release
      NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    steps:
    - name: Rest
      run: echo  NUGET_URL is ${{ env.NUGET_URL }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Add GitHub NuGet Source
      run: dotnet nuget add source ${{ env.NUGET_URL }} -n github -u ${{ secrets.REGISTRY_USER }}  -p ${{ secrets.REGISTRY_TOKEN }} --store-password-in-clear-text

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.FOLDER }}

    - name: Build AlphaTrust.NuGet
      run: msbuild ${{ env.SOLUTION }} /p:Configuration=${{ env.CONFIG }}

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION }} --configuration ${{ env.CONFIG }} --no-restore --no-build --verbosity normal

    - name: NuGet Push
      run: dotnet nuget push ${{ env.FOLDER }}/**/*.nupkg --source ${{ env.NUGET_URL }} --skip-duplicate
